In [1]:
import numpy as np

In [2]:
l = [23245, 27, 546, 215, -1234]
a = np.array(l)

In [3]:
a

array([23245,    27,   546,   215, -1234])

In [4]:
# Why arrays? Because you can't mix datatypes
# 

In [7]:
b = np.array([12, 455, 32, True, "abc"])
b

array(['12', '455', '32', 'True', 'abc'], dtype='<U21')

In [9]:
# Arrays also include many more methods than lists!
a.mean()

4559.8

In [10]:
l.mean()

AttributeError: 'list' object has no attribute 'mean'

In [11]:
# Matrice is a 2 dimensional array. 
# You need to work with arrays because you can get to tables and other
# useful things like dataframes

In [14]:
c = np.array([12.32, 232.23, 1, 23])
c

array([ 12.32, 232.23,   1.  ,  23.  ])

In [15]:
### Slicing Arrays
# we can do this with lists, we can do it with arrays too. Lists first

In [16]:
l

[23245, 27, 546, 215, -1234]

In [17]:
l[1:]

[27, 546, 215, -1234]

In [18]:
a[2:]

array([  546,   215, -1234])

In [19]:
# Same with arrays
a[2:3]

array([546])

In [20]:
# When you slice an array, you don't create a copy of it, you replace
# data inside the original array

In [24]:
b = a[2:4]
b

array([546, 215])

In [25]:
b[:] = 111

In [27]:
b

array([111, 111])

In [28]:
a

array([23245,    27,   111,   111, -1234])

In [29]:
a = c.copy()


In [30]:
c

array([ 12.32, 232.23,   1.  ,  23.  ])

In [31]:
a


array([ 12.32, 232.23,   1.  ,  23.  ])

In [ ]:
# CHAPTER RECAP